### ISSUE TITLE
Bug: Burn Resistance treats Kineticist level as 2 higher rather than 2 lower.

### ISSUE THREAD

**Issue by RainaThrownAway** [pheonix99/TomeOfTheFirebird#10]
As the title says. I'm playing an Elemental Engine Kineticist. Took the feat at level 7. I expected to take 5 non-lethal damage. Instead I take 9.
![Have the burn resistance feat](https://user-images.githubusercontent.com/52016965/212528374-091c69e0-0f49-46c2-8e3e-bbd7aaa478c9.jpg)
![Nine non lethal damage, level 7](https://user-images.githubusercontent.com/52016965/212528384-4247b678-f86d-4174-b629-0422bac4d51e.jpg)

I am running a long list of other mods, if you want my full mod list, I'll add it.

**Comment by pheonix99** [comment]
Oh that's definitely a me problem will get right on it.

**Comment by pheonix99** [comment]
Should be fixed.

**Comment by RainaThrownAway** [comment]
Yep, it's working now!
