### ISSUE TITLE
Disabling Spells doesn't disable the spells

### ISSUE THREAD

**Issue by Woffingshire** [pheonix99/TomeOfTheFirebird#11]
When disabling spells added by this mod, it does not actually make them disappear.
There are spells that are added by both this mod and Expanded Content. In the spell selection menu on level up it shows two of the same spell with slightly different descriptions and icons.
The spells from Expanded Content cannot be disabled, so I disable of them from this mod. However after disabling them and reloading/launching the game there are still two of the spell to choose from.

**Comment by pheonix99** [comment]
Ok, yeah, 95% sure I know why that's happening.
