### ISSUE TITLE
Tiefling Maw and Claw - Claw becomes unequiped

### ISSUE THREAD

**Issue by KrispyXIV** [pheonix99/TomeOfTheFirebird#12]
I noted that when attempting to use the tiefling alternate racial feature Maw and Claw to gain Claw attacks, inevitably something would cause the claws to become "unequiped" (I think leveling up), and unrecoverable.  Even removing the feature and readding it with Toybox didn't get my claws back.  

I've noted behavior similar to this with other claws in the core game, but almost all of those are toggled abilities which allows you to toggle them off and on to correct the issue.

**Comment by pheonix99** [comment]
Should be fixed in latest release - I just made it a toggle
