### ISSUE TITLE
Serpentine Bloodline request

### ISSUE THREAD

**Issue by LukasDF91** [pheonix99/TomeOfTheFirebird#17]
Hello, can you give the Fangs from the Serpentine Bloodline the same tweak you gave to the Claws from the Draconic Bloodlines? (Unlimited)

**Comment by pheonix99** [comment]
I'm retired from modding save for dealing with version incompatibilities for now.

Fangs is also a good deal stronger between the poison and not being a hand based weapon so I'm not at all sure on the balance there.
