### ISSUE TITLE
Missing teamwork feats in 2.1.2e

### ISSUE THREAD

**Issue by nixgnot** [pheonix99/TomeOfTheFirebird#19]
Coordinated Shoot  & Swarm Strike & Lastwall Phalanx disappeared in the feats list.
(tried to found them in full list or teamwork feats list, and no any feat that shown as blank in these list too.

and they become some "blank" icon for the character who already have it
![image](https://user-images.githubusercontent.com/20860979/230636764-985bd950-5fa8-4e62-8183-7baba32c402d.png)

**Comment by nixgnot** [comment]
more information:
tried have only Tome & TTCore actived. 

still happend.
![image](https://user-images.githubusercontent.com/20860979/230638261-91405814-06f4-4ba1-989c-8212f9b57ae3.png)

**Comment by pheonix99** [comment]
Side effect of everything exploding from an owlcat implementation change.

Fixed
