### ISSUE TITLE
Chains of Fire only deals damage to primary enemy

### ISSUE THREAD

**Issue by Woffingshire** [pheonix99/TomeOfTheFirebird#2]
Chains of fire doesn't seem to work as intended. Instead of dealing damage to every enemy it bounces to, it still bounces, but applies all of that damage to the first enemy it hit instead. If it hits 3 enemies enemy 1 takes damage 3 times while enemy 2 and 3 take nothing.

**Comment by pheonix99** [comment]
Ooops.

Will fix along with updating to 1.3 soon.

**Comment by pheonix99** [comment]
Should be fixed.
