### ISSUE TITLE
Feature Request: missing Kinetic Blade for Blood Kineticist's Blood Blast.

### ISSUE THREAD

**Issue by Seinra** [pheonix99/TomeOfTheFirebird#27]
Hello! As the tittle says, you never get this toggeable for the Blood Kineticist's Blood Blast, if you search for it with Toybox you'll find an unfinished toggeable, a copy-paste from the Charged Blast.

**Comment by pheonix99** [comment]
Ugh I'll see if I can fix I need to poke around with Blade for Kin Lancer anyway

**Comment by LukasDF91** [comment]
Dark Codex doesn't has a fix for this, I reported the problem to Fumihiko some weeks ago, he/she told me that "I'll will check it but can't promise you anything", and that was some updates ago so I think he/she couldn't found a fix, or she/he forgot to fix it.

**Comment by pheonix99** [comment]
Built.

Wasn't remotely tricky, just needed to create a missing near-zero-logic feature and set up adding it.
