### ISSUE TITLE
Blood Blast - Kinetic Blade bugs

### ISSUE THREAD

**Issue by Seinra** [pheonix99/TomeOfTheFirebird#29]
Hello, I found some bugs while testing the new kinetic blade with a Blood Kineticist character.

1) Visual Bug: the Blood Blast looks like the Water Blast, so the new Kinetic Blade should have the same visual as the Water Blast Kinetic Blade, but it it has the Charged Blast Kinetic Blade visual.

2) Wild Talent "Blade Whirlwind": when you "turn on" the Kinetic Blade toggeable for the Blood Blast, the "Blade Whirlwind" should get "illuminated" to show it is ready to be activated, this doesn't happen.

3) Infusion "Energize Weapon": this infusion is not working for the new Kinetic Blade because it is not adding the toggeable for the Blood Blast (it is the same bug that the Kinetic Blade had with the Blood Blast).

**Comment by pheonix99** [comment]
1: Ok, that should be simple.

2: ...Oh for the love of god are they looking for specific blades.

3: Energize Weapon is created by Dark Codex, out of scope, will not fix.

**Comment by pheonix99** [comment]
Fixed 1 I think - not released yet.

Fixed 2 I think - not released yet.

Have you attacked with it? I need to know if the inventory showing 0 damage is a UI glitch or a real thing.

**Comment by pheonix99** [comment]
Yeah the damage is frakked.

Cannot fix, blood kinetic blade is off the to-do list.
