### ISSUE TITLE
Discordant Song

### ISSUE THREAD

**Issue by NGottier42** [pheonix99/TomeOfTheFirebird#3]
Show's up blank in the feat selection screen initially. Seems to bug out that screen if I even so much as hover over it. If I select another feat, go forward, then go back it pulls the description proper but the screen is still bugged - visually it let's me select another feat (Discordant Song or not) but it doesn't change the actual feat selection when proceeding to the next screen.

![image](https://user-images.githubusercontent.com/44925991/173684688-640013f4-eb01-44fa-b710-eb4875fe862e.png)

![image](https://user-images.githubusercontent.com/44925991/173685695-b4cb6b9d-a3ff-4520-a04a-f6b84fc1d279.png)

**Comment by pheonix99** [comment]
Fixed!
