### ISSUE TITLE
New Spell：Blade Tutor's Spirit

### ISSUE THREAD

**Issue by knightddk** [pheonix99/TomeOfTheFirebird#30]
I think this is a powerful spell for magical warriors.

https://www.aonprd.com/SpellDisplay.aspx?ItemName=Blade%20Tutor%27s%20Spirit

**Comment by pheonix99** [comment]
It would be an incredible pain in the arse to code because I'd need to handle every applicable feat and things that cancel their bonuses manually.

Not happening.
