### ISSUE TITLE
Purifyer

### ISSUE THREAD

**Issue by CyrixReportsBugs** [pheonix99/TomeOfTheFirebird#31]
Is it possible to make the changes to the Oracles Healing/Harm Spells a toggle between the three states that kinda exist(ed)?

1. Owlbrew - cure/harm selection disabled for no gain
2. TTT compatible - only the first two cure spells (harm missing intentional?)
3. Non-TTT - reenable the full feature to choose between full cure/harm like all other oracles

Thank you for all your hard work!

**Comment by pheonix99** [comment]
The only reason I added that feature was as part of making purifier not strictly worse than base during act one.

Purifier losing the cure/inflict is from Paizo, not Owlbrew. Owlbrew is purifier not having its mystery spells swapped out.

Harm being missing is entirely intended yes.

This is working entirely as designed, will not change.
