### ISSUE TITLE
Issue: Chains of Fire Not Getting Certain Damage Bonuses

### ISSUE THREAD

**Issue by TKDancer** [pheonix99/TomeOfTheFirebird#32]
Chains of Fire isnt benefting from fire draconic bloodline arcanas or similar bonuses likely due to missing its fire descriptor? the toolcard says it has the descriptor but damage log says otherwise

in fact even with with elemental fire arcana(to change spell damage and type to fire) it still doesnt benefit from the above

**Comment by pheonix99** [comment]
Odd.

I can look into that

**Comment by pheonix99** [comment]
Should be fixed now.
