### ISSUE TITLE
infinite loading

### ISSUE THREAD

**Issue by thycrow** [pheonix99/TomeOfTheFirebird#41]
talbetops tweaks core infinite loading for game ver 2.2.1 when starting the game

**Comment by pheonix99** [comment]
Unable to replicate.

Can you give me your modlist?

**Comment by thycrow** [comment]
![modlist](https://github.com/pheonix99/TomeOfTheFirebird/assets/152589998/be364b53-aa4b-40b0-bb7a-fa71f88af67e)

**Comment by thycrow** [comment]
oops sorry wrong mod
