### ISSUE TITLE
Suggestion : Witches and patron tweaks/additions

### ISSUE THREAD

**Issue by Mythalar** [pheonix99/TomeOfTheFirebird#5]
Hello !

I only very recently discovered your mod and I'm very pleased by the new stuff so thank you :) 

Regarding the witch class, and since you already made some little changes and implemented new spells, I would suggest : 

- Replace the 8th lvl Insanity spell with the actual [Symbol of Insanity](https://www.d20pfsrd.com/magic/all-spells/s/symbol-of-insanity), I cannot even guess why there is Mass Cure instead...

- Implement the Death Patron since I think the necromancy witch is quite lacking, when it can be very RP nice (not every witch is Ember!). All spells are not in-game but an adaptation such as this can be good enough : 
Lvl 1 : [Ray of Enfeeblement](https://pathfinderwrathoftherighteous.wiki.fextralife.com/Ray+of+Enfeeblement)
Lvl 2 : [Blessing of Courage and Life](https://pathfinderwrathoftherighteous.wiki.fextralife.com/Blessing+of+Courage+and+Life) to be TT true, [Boneshaker](https://pathfinderwrathoftherighteous.wiki.fextralife.com/Boneshaker) to be more usefull
Lvl 3 : Gloomblind bolts !
Lvl 4 : [Boneshatter](https://pathfinderwrathoftherighteous.wiki.fextralife.com/Boneshatter)
Lvl 5 : [Wracking Ray](https://pathfinderwrathoftherighteous.wiki.fextralife.com/Wracking+Ray)
Lvl 6 : [Circle of Death](https://pathfinderwrathoftherighteous.wiki.fextralife.com/Circle+of+Death)
Lvl 7 : [Finger of Death](https://pathfinderwrathoftherighteous.wiki.fextralife.com/Finger+of+Death)
Lvl 8 : [Horrid Wilting](https://pathfinderwrathoftherighteous.wiki.fextralife.com/Horrid+Wilting)
Lvl 8 : I would personnaly go for [Wail of the Banshee](https://pathfinderwrathoftherighteous.wiki.fextralife.com/Wail+of+the+Banshee) instead of [Power Word Kill](https://pathfinderwrathoftherighteous.wiki.fextralife.com/Power+Word+Kill) that is not very useful in WotR but well...

- Implement the [Witch Knife feat](https://www.d20pfsrd.com/feats/general-feats/witch-knife) for the +1 DC (possibly to suppress material component if any, like Circle of death? Don't know if doable)

( on the homebrew side, that I personnaly use in TT, it would be cool to add to the witch the ability to spontaneously expand a prepared spell to cast a Patron spell of the same level or lower (this feature is implemented by Stari0n in the MagicTime mod for the Pact Wizard). I would argue that's not really stretchy to add it as a base feature but a feat (or curse?) or else can be good too.
Note :  Stari0in implementation does not allow to spontaneously cast Patron spells modified by metamagic, which is really a loss, so it would be perfect if feasible (IIRC the Call of the Wild Kingmaker mod implemented the Pact Wizard and other archetypes with this feature and allowed it, same for Greater Spell Specialization) )

Well, even without it thank you again for your work :)

Sorry if I am not very clear, not a native speaker -_-

**Comment by pheonix99** [comment]
Ooooh I didn't realize death patron was fully in game. Will implement.

**Comment by Mythalar** [comment]
Yes I agree with you on this point, hence I mentioned more Blasty/ray spells that would be useful and still not broken (some foes are immuned to death effects so it's more or less balanced)

**Comment by pheonix99** [comment]
Death Patron is done.

**Comment by Mythalar** [comment]
Oh yeah that's nice finally a necro witch !

Thanks a lot I made a ray of death build :)

Would you consider some of the other suggestion? (asking for a friend :p )

A bit sad that Stari0n [MagicTime mod](https://github.com/Stari0n/MagicTime) does not allow custom patrons but still very nice !

**Comment by pheonix99** [comment]
I would normally but I'm neck deep in writing a mod to bring [Path Of War](https://www.d20pfsrd.com/alternative-rule-systems/path-of-war/) to this game so anything that requires significant logic work and doesn't contribute to that is just not happening ATM.

**Comment by Mythalar** [comment]
Oh that's nice !
And I'm in no rush or anything, was asking since the topic was still open.

Path of war system would be a very cool addition.
