### ISSUE TITLE
[Bug report] News spells and spell specialization

### ISSUE THREAD

**Issue by Mythalar** [pheonix99/TomeOfTheFirebird#6]
Hello !

Just saw that the news spells cannot be seleted with Spell Specialisation, which can be an issue by itself.
On top of this thoses cannot be used with other feats (added by other mods) that use the spell specialization choice list.

Thanks =)

**Comment by pheonix99** [comment]
I have *no idea* how on god's green earth to fix this but I'll ask around.

**Comment by Mythalar** [comment]
I guess Truinto knows since he based some of her s new feats on spell specialization!

**Comment by Mythalar** [comment]
Hey, tested it right now and it's working like a charm :)

**Comment by pheonix99** [comment]
Great!
