### ISSUE TITLE
Is this mod compatible with latest game version?

### ISSUE THREAD

**Issue by Majber** [pheonix99/TomeOfTheFirebird#7]
Is this mod compatible with latest game version?

**Comment by pheonix99** [comment]
I have no idea at the moment.

I'll try to get to it eventually but my interest in this game is largely shot. Xenoblade happened to it.

**Comment by Mythalar** [comment]
No need to before the EE kicks in I guess ^^

**Comment by pheonix99** [comment]
It should be now!
