### ISSUE TITLE
Dispels Are Buff Safe - not working for baleful polymorph and alchemist bombs

### ISSUE THREAD

**Issue by Fiddydamage** [pheonix99/TomeOfTheFirebird#8]
When enabling the "dispels are buff safe", Dispel Magic (target) will no longer attempt a dispel check on Baleful polymorph. 

Also, any chance of adding the Alchemist Dispelling bombs to the "doesn't dispel friendly buffs"? 

I was also having trouble removing the condition "sickened" the other day, but I don't know if sickened is related to this or not.

![image](https://user-images.githubusercontent.com/93052591/198703318-93f5158e-5b23-4a56-8468-fb5090d05756.png)

![image](https://user-images.githubusercontent.com/93052591/198703843-ee99da15-cba7-4c74-83ab-975766107381.png)

**Comment by pheonix99** [comment]
That's an Owlcat screwup with setting friendly-or-not on BP.

If I ever get back to modding this game I'll add a patch still.

Sickened is a condition not a spell effect dispel should only remove as part of dispelling a spell that causes it.

**Comment by pheonix99** [comment]
Should be fixed for dispelling bombs.

Check and see if the baleful polymorph issue still exists - the BP looks like that shouldn't be an issue?
