### ISSUE TITLE
Prodigious TWF Does Not Apply to Two Weapon Defense

### ISSUE THREAD

**Issue by expressfreely** [pheonix99/TomeOfTheFirebird#9]
You may fight with a one-handed weapon in your offhand as if it were a light weapon. In addition, you may use your [Strength] score instead of your [Dexterity] score for the purpose of qualifying for [Two-Weapon Fighting] **and any feats with Two-Weapon Fighting as a prerequisite.**

That last bit makes it clear that Two Weapon Defense should qualify. I know you're not really working on the game atm but this would be a nice fix.

**Comment by pheonix99** [comment]
Should be fixed in new version.
